# Generated by Django 5.0.6 on 2024-08-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
    ]
